[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.5
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[window]
dimensions = { columns = 140, lines = 30 }
padding = { x = 7, y = 7 }
dynamic_padding = true
decorations = "Full" # "Full" | "None" | "Transparent" | "Buttonless"
opacity = 1.0
blur = true

[scrolling]
history = 10000
multiplier = 1 # 3

[bell]
animation = "Ease"
duration = 5

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
unfocused_hollow = true
thickness = 0.15 # 0.0 - 1.p

[mouse]
hide_when_typing = true

[terminal]
shell.program = "/bin/zsh"

[keyboard]
bindings = [
  # { <key>, <mods>, <mode>, <command> },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]
