set -s escape-time 0
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set-option -g set-clipboard on

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set-option -sa terminal-overrides ",xterm*:Tc"

set -g history-limit 50000
set -g focus-events on
set -g renumber-windows on

# Reload config
bind -N "Reload tmux config" r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

# Quick session management
bind -N "Create new session" S command-prompt -p "New session:" "new-session -s '%%'"
bind -N "Kill current session" X confirm-before -p "Kill session #S? (y/n)" kill-session

#### COPY MODE (vi) #######################################
setw -g mode-keys vi
bind -N "Copy mode: start selection" -T copy-mode-vi v send-keys -X begin-selection
bind -N "Copy mode: yank selection" -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -N "Copy mode: yank reactangle selection" -T copy-mode-vi C-v send-keys -X rectangle-toggle

# Create a new window in the current directory
bind c new-window -c "#{pane_current_path}"

# Keep new panes in the current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Navigate panes with Alt + arrow keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Resize panes with Prefix + arrow keys
bind Left resize-pane -L 5
bind Right resize-pane -R 5
bind Up resize-pane -U 5
bind Down resize-pane -D 5

# Status bar
set -g status-position bottom
set -g status-style "bg=default,fg=white"
set -g status-left "#[bold] #S "
set -g status-right "%Y-%m-%d %H:%M"
set -g status-left-length 30

# Window titles
# setw -g window-status-format " #I:#W "
# setw -g window-status-current-format " #[bold]#I:#W#[default] "
