[mgr]
ratio = [1,4,3]
sort_by = 'natural'
show_hidden = true
show_symlink = true
mouse_events = [ "click", "scroll" , 'touch']

[input]
cd_origin = "bottom-left"
create_origin = "bottom-left"
rename_origin = "bottom-left"
filter_origin = "bottom-left"
find_origin = "bottom-left"
search_origin = "bottom-left"
shell_origin = "bottom-left"
