theme = "catppuccin_mocha"

[editor]
cursorline = true
auto-save = true
auto-format = true
bufferline = "multiple"
color-modes = true
completion-replace = true
line-number = "relative"
mouse = false
true-color = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 0
character = "▏" # Some characters that work well: "▏", "┆", "┊", "╎"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = false

[keys.normal.g]
d = "goto_last_modification"

[keys.normal]
C-s = ":write"

[keys.normal.space]
w = { w = ":write" }
q = { q = ":wqa" }

[keys.insert]
C-s = ":write"

[keys.select]
C-s = ":write"
