[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
comment-token = "#"
language-servers = [ "taplo" ]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "lua"
injection-regex = "lua"
scope = "source.lua"
file-types = ["lua", "rockspec"]
shebangs = ["lua", "luajit"]
roots = [".luarc.json", ".luacheckrc", ".stylua.toml", "selene.toml", ".git"]
comment-token = "--"
block-comment-tokens = { start = "--[[", end = "--]]" }
indent = { tab-width = 2, unit = "  " }
# formatter = { command = "stylua" , args = ["--stdin"] }
formatter = { command = "stylua", args = ["-"] }
language-servers = [ "lua-language-server" ]
